#!/usr/bin/env python3
"""Generate docs/COMMANDS.md from the agent tool schema (contracts §7,
§8): every tool with its parameters, and its CLI and UI equivalent.

    .venv/bin/python scripts/agent_commands.py            # writes docs/COMMANDS.md
    .venv/bin/python scripts/agent_commands.py --check    # exit 1 when the doc is stale

The doc is generated, never edited by hand: ``tests/test_agent.py``
runs the generator and compares byte for byte.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from core.agent.tools import EQUIVALENTS, TOOL_NAMES, schemas  # noqa: E402

DOC = REPO / "docs" / "COMMANDS.md"


def _type(schema: dict) -> str:
    kind = schema.get("type")
    if isinstance(kind, list):
        return " or ".join(str(k) for k in kind)
    return str(kind) if kind else "any"


def render() -> str:
    lines = [
        "# Commands -- every tool, its CLI and its page equivalent",
        "",
        "*Generated by `scripts/agent_commands.py` from the tool schema in",
        "`core/agent/tools.py` (contracts §7). Do not edit by hand; run the",
        "script. The agent (`python -m flightsim.agent`), the CLIs and the",
        "web app are three doors onto the same library; a screen's command",
        "is the one named here.*",
        "",
        "    python -m flightsim.agent \"<prompt>\" --images N --out DIR [--format F] [--vary WORDS]",
        "",
        "Every tool call is checked by the authority policy (`authority.stated_field`,",
        "`authority.validation_token`, `authority.refusal_is_not_a_run`,",
        "`authority.budget`) and written to `DIR/trace.jsonl` as",
        "`{t, tool, input, output, reason, policy}`.",
        "",
    ]
    for schema in schemas():
        name = schema["name"]
        equivalent = EQUIVALENTS[name]
        lines.append(f"## `{name}`")
        lines.append("")
        lines.append(schema["description"])
        lines.append("")
        lines.append("| parameter | type | required | default |")
        lines.append("|---|---|---|---|")
        props = schema["parameters"]["properties"]
        required = set(schema["parameters"]["required"])
        for pname, pschema in props.items():
            default = ("" if pname in required
                       else json.dumps(pschema.get("default"), default=str))
            lines.append(f"| `{pname}` | {_type(pschema)} | "
                         f"{'yes' if pname in required else 'no'} | {default} |")
        lines.append("")
        lines.append(f"* **CLI:** `{equivalent['cli']}`")
        lines.append(f"* **UI:** {equivalent['ui']}")
        lines.append("")
    lines.append("## The schema, verbatim")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(schemas(), indent=1))
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when docs/COMMANDS.md differs from the generator")
    parser.add_argument("--out", default=str(DOC))
    args = parser.parse_args(argv)
    text = render()
    assert set(EQUIVALENTS) == set(TOOL_NAMES), "every tool needs a CLI/UI equivalent"
    path = Path(args.out)
    if args.check:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current != text:
            print(f"{path} is stale; run scripts/agent_commands.py")
            return 1
        print(f"{path} is current")
        return 0
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
